/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Luna
 */
public class PanelInicio extends javax.swing.JPanel {

    /**
     * Creates new form PanelInicio
     */
    public PanelInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cardClientes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cardProductos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cardVentas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jPanelActividad = new javax.swing.JPanel();
        jLabelAR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAactividadReciente = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(1067, 306));
        setName("panelInicio"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1067, 306));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTitulo1.setText("¡ BIENVENIDO !");
        add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Sistema de Gestión");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 130, -1));

        cardClientes.setBackground(new java.awt.Color(255, 255, 255));
        cardClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));
        cardClientes.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Clientes");

        javax.swing.GroupLayout cardClientesLayout = new javax.swing.GroupLayout(cardClientes);
        cardClientes.setLayout(cardClientesLayout);
        cardClientesLayout.setHorizontalGroup(
            cardClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardClientesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        cardClientesLayout.setVerticalGroup(
            cardClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardClientesLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        add(cardClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 100));

        cardProductos.setBackground(new java.awt.Color(255, 255, 255));
        cardProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));
        cardProductos.setForeground(new java.awt.Color(0, 0, 0));
        cardProductos.setPreferredSize(new java.awt.Dimension(100, 60));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Productos");

        javax.swing.GroupLayout cardProductosLayout = new javax.swing.GroupLayout(cardProductos);
        cardProductos.setLayout(cardProductosLayout);
        cardProductosLayout.setHorizontalGroup(
            cardProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProductosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        cardProductosLayout.setVerticalGroup(
            cardProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProductosLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        add(cardProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 100));

        cardVentas.setBackground(new java.awt.Color(255, 255, 255));
        cardVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));
        cardVentas.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ventas");

        javax.swing.GroupLayout cardVentasLayout = new javax.swing.GroupLayout(cardVentas);
        cardVentas.setLayout(cardVentasLayout);
        cardVentasLayout.setHorizontalGroup(
            cardVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardVentasLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(24, 24, 24))
        );
        cardVentasLayout.setVerticalGroup(
            cardVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardVentasLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        add(cardVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 90, 100));

        jLabelFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelFecha.setText("Fecha: 18/05/2026");
        add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 112, -1));

        jPanelActividad.setName("panelActividad"); // NOI18N

        jLabelAR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelAR.setText("Actividad Reciente");

        txtAactividadReciente.setEditable(false);
        txtAactividadReciente.setColumns(20);
        txtAactividadReciente.setRows(5);
        txtAactividadReciente.setText("• Cliente agregado\n• Venta registrada\n• Cola actualizada\n• Producto modificado");
        txtAactividadReciente.setBorder(null);
        jScrollPane1.setViewportView(txtAactividadReciente);

        javax.swing.GroupLayout jPanelActividadLayout = new javax.swing.GroupLayout(jPanelActividad);
        jPanelActividad.setLayout(jPanelActividadLayout);
        jPanelActividadLayout.setHorizontalGroup(
            jPanelActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActividadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAR, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelActividadLayout.setVerticalGroup(
            jPanelActividadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActividadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        add(jPanelActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 400, 180));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardClientes;
    private javax.swing.JPanel cardProductos;
    private javax.swing.JPanel cardVentas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAR;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanelActividad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAactividadReciente;
    // End of variables declaration//GEN-END:variables
}
