/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista2;

import Controladores.ControlPedido;
import Modelo.Pedido;
import Estructuras.Nodo;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;

public class panelPedidos extends javax.swing.JPanel {

    /**
     * Creates new form panelPedidos
     */
    private ControlPedido controlador;

    public panelPedidos() {
        initComponents();
        controlador = new ControlPedido();
        cargarTabla();
    }

    //METODO
    private void cargarTabla() {

        DefaultTableModel modelo
                = (DefaultTableModel) tblPedidos.getModel();

        modelo.setRowCount(0);

        Nodo<Pedido> aux
                = controlador.getPedidos().getFrenteNodo();

        while (aux != null) {

            Pedido p = aux.getDato();

            modelo.addRow(new Object[]{
                p.getIdPedido(),
                p.getCliente(),
                p.getFecha(),
                p.getTotal(),
                p.getEstado(),
                ""
            });

            aux = aux.getSiguiente();
        }
    }

    //METODO PARA AGREGAR PEDIDO
    private void mostrarDialogoNuevoPedido() {

        JTextField txtId = new JTextField();
        JTextField txtCliente = new JTextField();
        JTextField txtFecha = new JTextField();
        JTextField txtTotal = new JTextField();

        String[] estados = {
            "Pendiente",
            "En Proceso",
            "Completado",
            "Cancelado"
        };

        JComboBox<String> cmbEstado
                = new JComboBox<>(estados);

        Object[] campos = {
            "ID Pedido:", txtId,
            "Cliente:", txtCliente,
            "Fecha:", txtFecha,
            "Total:", txtTotal,
            "Estado:", cmbEstado
        };

        int respuesta = JOptionPane.showConfirmDialog(
                this,
                campos,
                "Nuevo Pedido",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (respuesta == JOptionPane.OK_OPTION) {

            try {

                Pedido pedido = new Pedido(
                        txtId.getText().trim(),
                        txtCliente.getText().trim(),
                        txtFecha.getText().trim(),
                        Double.parseDouble(
                                txtTotal.getText().trim()),
                        (String) cmbEstado.getSelectedItem()
                );

                controlador.agregarPedido(pedido);

                cargarTabla();

                JOptionPane.showMessageDialog(
                        this,
                        "Pedido agregado correctamente."
                );

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(
                        this,
                        "El total debe ser numérico."
                );
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInventario = new javax.swing.JLabel();
        lblSubtitulo3 = new javax.swing.JLabel();
        btnNuevoPedido = new javax.swing.JButton();
        btnEnProceso = new javax.swing.JButton();
        btnPendientes = new javax.swing.JButton();
        btnCancelados = new javax.swing.JButton();
        btnCompletados = new javax.swing.JButton();
        panelPedidoss = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        panelDetallePedido = new javax.swing.JPanel();
        jLabel1e = new javax.swing.JLabel();
        jLabel1e1 = new javax.swing.JLabel();
        jScrollPaneDetallePedido = new javax.swing.JScrollPane();
        tablaDetallePedido = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 249, 251));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        lblInventario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblInventario.setForeground(new java.awt.Color(17, 24, 39));
        lblInventario.setText("Gestión de Pedidos");
        lblInventario.setAlignmentX(40.0F);
        lblInventario.setAlignmentY(25.0F);

        lblSubtitulo3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitulo3.setForeground(new java.awt.Color(17, 24, 39));
        lblSubtitulo3.setText("Administra y procesa los pedidos de los clientes.");

        btnNuevoPedido.setBackground(new java.awt.Color(179, 227, 4));
        btnNuevoPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoPedido.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevoPedido.setText("+ Nuevo Pedido");
        btnNuevoPedido.setAlignmentX(780.0F);
        btnNuevoPedido.setAlignmentY(35.0F);
        btnNuevoPedido.setPreferredSize(new java.awt.Dimension(160, 40));
        btnNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPedidoActionPerformed(evt);
            }
        });

        btnEnProceso.setBackground(new java.awt.Color(0, 0, 0));
        btnEnProceso.setForeground(new java.awt.Color(179, 227, 4));
        btnEnProceso.setText("En Proceso");
        btnEnProceso.setPreferredSize(new java.awt.Dimension(120, 35));

        btnPendientes.setBackground(new java.awt.Color(0, 0, 0));
        btnPendientes.setForeground(new java.awt.Color(179, 227, 4));
        btnPendientes.setText("Pendientes");
        btnPendientes.setPreferredSize(new java.awt.Dimension(120, 35));

        btnCancelados.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelados.setForeground(new java.awt.Color(179, 227, 4));
        btnCancelados.setText("Cancelados");
        btnCancelados.setPreferredSize(new java.awt.Dimension(120, 35));
        btnCancelados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanceladosActionPerformed(evt);
            }
        });

        btnCompletados.setBackground(new java.awt.Color(0, 0, 0));
        btnCompletados.setForeground(new java.awt.Color(179, 227, 4));
        btnCompletados.setText("Completados");
        btnCompletados.setPreferredSize(new java.awt.Dimension(120, 35));

        panelPedidoss.setBackground(new java.awt.Color(255, 255, 255));
        panelPedidoss.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                panelPedidossComponentAdded(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblPedidos.setBackground(new java.awt.Color(255, 255, 255));
        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pedido", "Cliente", "Fecha", "Total", "Estado", "Acciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPedidos);
        if (tblPedidos.getColumnModel().getColumnCount() > 0) {
            tblPedidos.getColumnModel().getColumn(0).setResizable(false);
            tblPedidos.getColumnModel().getColumn(1).setResizable(false);
            tblPedidos.getColumnModel().getColumn(2).setResizable(false);
            tblPedidos.getColumnModel().getColumn(3).setResizable(false);
            tblPedidos.getColumnModel().getColumn(4).setResizable(false);
            tblPedidos.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout panelPedidossLayout = new javax.swing.GroupLayout(panelPedidoss);
        panelPedidoss.setLayout(panelPedidossLayout);
        panelPedidossLayout.setHorizontalGroup(
            panelPedidossLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panelPedidossLayout.setVerticalGroup(
            panelPedidossLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelDetallePedido.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1e.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1e.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1e.setText("Detalle del  Pedido #");

        jLabel1e1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1e1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1e1.setText("Total: S/ ");

        jScrollPaneDetallePedido.setBackground(new java.awt.Color(255, 255, 255));

        tablaDetallePedido.setBackground(new java.awt.Color(255, 255, 255));
        tablaDetallePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unit.", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneDetallePedido.setViewportView(tablaDetallePedido);
        if (tablaDetallePedido.getColumnModel().getColumnCount() > 0) {
            tablaDetallePedido.getColumnModel().getColumn(0).setResizable(false);
            tablaDetallePedido.getColumnModel().getColumn(1).setResizable(false);
            tablaDetallePedido.getColumnModel().getColumn(2).setResizable(false);
            tablaDetallePedido.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout panelDetallePedidoLayout = new javax.swing.GroupLayout(panelDetallePedido);
        panelDetallePedido.setLayout(panelDetallePedidoLayout);
        panelDetallePedidoLayout.setHorizontalGroup(
            panelDetallePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallePedidoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1e)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1e1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPaneDetallePedido, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelDetallePedidoLayout.setVerticalGroup(
            panelDetallePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallePedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallePedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1e, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1e1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDetallePedido, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCompletados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 409, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSubtitulo3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelDetallePedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPedidoss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInventario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventario)
                    .addComponent(btnNuevoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo3)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompletados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPedidoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDetallePedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanceladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanceladosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCanceladosActionPerformed

    private void panelPedidossComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_panelPedidossComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panelPedidossComponentAdded

    private void btnNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPedidoActionPerformed
        mostrarDialogoNuevoPedido();
    }//GEN-LAST:event_btnNuevoPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelados;
    private javax.swing.JButton btnCompletados;
    private javax.swing.JButton btnEnProceso;
    private javax.swing.JButton btnNuevoPedido;
    private javax.swing.JButton btnPendientes;
    private javax.swing.JLabel jLabel1e;
    private javax.swing.JLabel jLabel1e1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneDetallePedido;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblSubtitulo3;
    private javax.swing.JPanel panelDetallePedido;
    private javax.swing.JPanel panelPedidoss;
    private javax.swing.JTable tablaDetallePedido;
    private javax.swing.JTable tblPedidos;
    // End of variables declaration//GEN-END:variables
}
