/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista2;


import Controladores.ControlProducto;
import Estructuras.Nodo;
import Modelo.Producto;
import javax.security.auth.callback.TextOutputCallback;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class panelProductos extends javax.swing.JPanel {

    /**
     * Creates new form panelProductos
     */
    
    private ControlProducto controlador;
    
    public panelProductos() {
        initComponents();
        controlador = new ControlProducto();
        cargarTabla();              
    }
    
    private void cargarTabla(){
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();

        modelo.setRowCount(0);

        Nodo<Producto> temp = controlador.getProductos().getCabeza();

        while (temp != null) {

            Producto p = temp.getDato();

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNombre(),
                p.getCategoria(),
                p.getPrecio(),
                p.getStock()
            });

            temp = temp.getSiguiente();
        }

        lblTotalProductos.setText(
                "Total de productos: "+ controlador.getProductos().tamaño()
        );
    }
    
    //BUSCAR POR NOMBRE O CODIGO
    private void buscarProducto() {
        
        String texto = txtBuscar.getText().trim();
        
        if (texto.isEmpty()) {
            cargarTabla();
        return;
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();

        modelo.setRowCount(0);

        Nodo<Producto> temp = controlador.buscarProductos(texto).getCabeza();

        while (temp != null) {
        Producto p = temp.getDato();

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNombre(),
                p.getCategoria(),
                p.getPrecio(),
                p.getStock()
            });

            temp = temp.getSiguiente();
        }
    }
    
    //FILTRAR POR CATEGORIA
    private void filtrarPorCategoria() {

        String categoria = cmbCategoria.getSelectedItem().toString();

        DefaultTableModel modelo = (DefaultTableModel) tblProductos.getModel();

        modelo.setRowCount(0);

        Nodo<Producto> temp = controlador.getProductos().getCabeza();

        while (temp != null) {

        Producto p = temp.getDato();

        if (categoria.equals("Todas")
                || p.getCategoria().equalsIgnoreCase(categoria)) {

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNombre(),
                p.getCategoria(),
                p.getPrecio(),
                p.getStock()
            });
        }

        temp = temp.getSiguiente();
        }
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSubtitulo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo1 = new javax.swing.JLabel();
        btnNuevoProducto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblTotalProductos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(17, 24, 39));
        lblSubtitulo.setText("Resumen general del sistema");

        setBackground(new java.awt.Color(245, 247, 250));
        setName("panelProductos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 700));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(17, 24, 39));
        lblTitulo.setText("Gestión de Productos");
        lblTitulo.setAlignmentX(40.0F);
        lblTitulo.setAlignmentY(25.0F);

        lblSubtitulo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitulo1.setForeground(new java.awt.Color(17, 24, 39));
        lblSubtitulo1.setText("Administra el catálogo de productos de la tienda.");

        btnNuevoProducto.setBackground(new java.awt.Color(179, 227, 4));
        btnNuevoProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevoProducto.setText("+ Nuevo Producto");
        btnNuevoProducto.setAlignmentX(780.0F);
        btnNuevoProducto.setAlignmentY(35.0F);
        btnNuevoProducto.setPreferredSize(new java.awt.Dimension(160, 40));
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(30.0F);
        jPanel1.setAlignmentY(100.0F);
        jPanel1.setName("panelContenidoProductos"); // NOI18N

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(153, 153, 153));
        txtBuscar.setText("   ");
        txtBuscar.setAlignmentX(20.0F);
        txtBuscar.setAlignmentY(20.0F);
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Categoría:");
        jLabel1.setAlignmentX(650.0F);
        jLabel1.setAlignmentY(25.0F);

        cmbCategoria.setBackground(new java.awt.Color(255, 255, 255));
        cmbCategoria.setForeground(new java.awt.Color(0, 0, 0));
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Polos", "Shorts", "Casacas", "Buzos", "Accesorios" }));
        cmbCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        cmbCategoria.setPreferredSize(new java.awt.Dimension(100, 35));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        tblProductos.setBackground(new java.awt.Color(255, 255, 255));
        tblProductos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        tblProductos.setForeground(new java.awt.Color(0, 0, 0));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Categoría", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setPreferredSize(new java.awt.Dimension(850, 320));
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(0).setResizable(false);
            tblProductos.getColumnModel().getColumn(1).setResizable(false);
            tblProductos.getColumnModel().getColumn(2).setResizable(false);
            tblProductos.getColumnModel().getColumn(3).setResizable(false);
            tblProductos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(179, 227, 4));
        btnEliminar.setText("🗑️ Eliminar");
        btnEliminar.setAlignmentX(780.0F);
        btnEliminar.setAlignmentY(35.0F);
        btnEliminar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 0, 0));
        btnEditar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(179, 227, 4));
        btnEditar.setText("✏ ️Editar");
        btnEditar.setAlignmentX(780.0F);
        btnEditar.setAlignmentY(35.0F);
        btnEditar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblTotalProductos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalProductos.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalProductos.setText("Total de productos: 0");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("🔍 Buscar producto. . .");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalProductos)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTotalProductos))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSubtitulo1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(btnNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        // METODO PARA MOSTRAR FORMULARIO
        mostrarDialogoNuevoProducto();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tblProductos.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(this, "Seleccione un producto.");

            return;
        }

        String codigo = tblProductos.getValueAt(fila, 0).toString();

        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Desea eliminar el producto?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {

            controlador.eliminarProducto(codigo);

            cargarTabla();

            JOptionPane.showMessageDialog(this,"Producto eliminado.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        int fila = tblProductos.getSelectedRow();

        if (fila == -1) {

            JOptionPane.showMessageDialog(this,"Seleccione un producto.");

        return;
        }

        String codigo = tblProductos.getValueAt(fila, 0).toString();

        Producto producto = controlador.buscarPorCodigo(codigo);

        if (producto == null) {
            return;
        }

        JTextField txtNom = new JTextField(producto.getNombre());
        JTextField txtPre = new JTextField(String.valueOf(producto.getPrecio()));
        JTextField txtSto = new JTextField(String.valueOf(producto.getStock()));

        String[] categorias = {
            "Polos",
            "Shorts",
            "Casacas",
            "Buzos",
            "Accesorios"
        };

        JComboBox<String> cmbCat = new JComboBox<>(categorias);

        cmbCat.setSelectedItem(producto.getCategoria());

        Object[] campos = {
            "Código:", producto.getCodigo(),
            "Nombre:", txtNom,
            "Categoría:", cmbCat,
            "Precio:", txtPre,
            "Stock:", txtSto
        };

        int respuesta = JOptionPane.showConfirmDialog(
            this,
            campos,
            "Editar Producto",
            JOptionPane.OK_CANCEL_OPTION
        );

        if (respuesta == JOptionPane.OK_OPTION) {

            try {

                Producto actualizado = new Producto(
                            producto.getCodigo(),
                            txtNom.getText().trim(),
                            (String) cmbCat.getSelectedItem(),
                            Double.parseDouble(
                                    txtPre.getText().trim()),
                            Integer.parseInt(
                                    txtSto.getText().trim())
                );

                controlador.actualizarProducto(actualizado);

                cargarTabla();

                JOptionPane.showMessageDialog(
                    this,
                    "Producto actualizado."
            );

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(
                    this,
                    "Precio y stock deben ser numéricos."
            );
        }
    }
                  
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        filtrarPorCategoria();
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        buscarProducto();
    }//GEN-LAST:event_txtBuscarActionPerformed

    //METODO AGREGAR PRODUCTO
    private void mostrarDialogoNuevoProducto() {

        JTextField txtCod = new JTextField();
        JTextField txtNom = new JTextField();
        JTextField txtPre = new JTextField();
        JTextField txtSto = new JTextField();

        String[] cats = {"Polos", "Shorts", "Casacas", "Buzos", "Accesorios"};
        JComboBox<String> cmbCat = new JComboBox<>(cats);

        Object[] campos = {
            "Código:", txtCod,
            "Nombre:", txtNom,
            "Categoría:", cmbCat,
            "Precio:", txtPre,
            "Stock:", txtSto
        };

        int r = JOptionPane.showConfirmDialog(
            this,
            campos,
            "Nuevo Producto",
            JOptionPane.OK_CANCEL_OPTION
        );

        if (r == JOptionPane.OK_OPTION) {

            try {

                Producto producto = new Producto(
                    txtCod.getText().trim(),
                    txtNom.getText().trim(),
                    (String) cmbCat.getSelectedItem(),
                    Double.parseDouble(txtPre.getText().trim()),
                    Integer.parseInt(txtSto.getText().trim())
                );

                controlador.agregarProducto(producto);

                cargarTabla();

                JOptionPane.showMessageDialog(
                    this,
                    "Producto agregado correctamente."
                );

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(
                    this,
                    "Precio y stock deben ser numéricos."
                );
            }
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblSubtitulo1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalProductos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
