/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista2;

import Controladores.ControlPedido;
import Controladores.ControlProducto;
import Controladores.DatosSistema;
import Estructuras.Nodo;
import Modelo.Movimiento;
import Modelo.Producto;
import java.time.LocalDate;

import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.JOptionPane;

public class panelInventario extends javax.swing.JPanel {

    /**
     * Creates new form panelInventario
     */
    private ControlProducto controlProducto = DatosSistema.controlProducto;

    private ControlPedido controlPedido = DatosSistema.controlPedido;

    public panelInventario() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        lblInventario = new javax.swing.JLabel();
        lblSubtitulo3 = new javax.swing.JLabel();
        btnActualizarInventario = new javax.swing.JButton();
        cardStock = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        lblStockTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardEntradas = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lblEntradas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cardSalidas = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        lblSalidas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cardProductos = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelMovimientos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMovimientos = new javax.swing.JTable();
        btnEntradaInventario = new javax.swing.JButton();

        jLabel13.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("📈 Actividad reciente");

        setBackground(new java.awt.Color(248, 249, 251));
        setName("panelInventario"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 700));

        lblInventario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblInventario.setForeground(new java.awt.Color(17, 24, 39));
        lblInventario.setText("Gestión de Inventario");
        lblInventario.setAlignmentX(40.0F);
        lblInventario.setAlignmentY(25.0F);

        lblSubtitulo3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtitulo3.setForeground(new java.awt.Color(17, 24, 39));
        lblSubtitulo3.setText("Controla el stock y los movimientos de inventario");

        btnActualizarInventario.setBackground(new java.awt.Color(179, 227, 4));
        btnActualizarInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarInventario.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizarInventario.setText("⟳ Actualizar");
        btnActualizarInventario.setAlignmentX(780.0F);
        btnActualizarInventario.setAlignmentY(35.0F);
        btnActualizarInventario.setPreferredSize(new java.awt.Dimension(160, 40));
        btnActualizarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarInventarioActionPerformed(evt);
            }
        });

        cardStock.setBackground(new java.awt.Color(255, 255, 255));
        cardStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        cardStock.setAlignmentX(40.0F);
        cardStock.setAlignmentY(110.0F);
        cardStock.setName("cardStockTotal"); // NOI18N
        cardStock.setPreferredSize(new java.awt.Dimension(190, 160));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Stock Total");

        lblStockTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblStockTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblStockTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStockTotal.setText("350");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Unidades");

        javax.swing.GroupLayout cardStockLayout = new javax.swing.GroupLayout(cardStock);
        cardStock.setLayout(cardStockLayout);
        cardStockLayout.setHorizontalGroup(
            cardStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardStockLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(lblStockTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardStockLayout.setVerticalGroup(
            cardStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardStockLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(lblStockTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(15, 15, 15))
        );

        cardEntradas.setBackground(new java.awt.Color(255, 255, 255));
        cardEntradas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        cardEntradas.setAlignmentX(40.0F);
        cardEntradas.setAlignmentY(110.0F);
        cardEntradas.setName("cardStockTotal"); // NOI18N
        cardEntradas.setPreferredSize(new java.awt.Dimension(190, 160));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Entradas");

        lblEntradas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblEntradas.setForeground(new java.awt.Color(0, 0, 0));
        lblEntradas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEntradas.setText("350");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Este mes");

        javax.swing.GroupLayout cardEntradasLayout = new javax.swing.GroupLayout(cardEntradas);
        cardEntradas.setLayout(cardEntradasLayout);
        cardEntradasLayout.setHorizontalGroup(
            cardEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEntradasLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel5)
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(lblEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardEntradasLayout.setVerticalGroup(
            cardEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardEntradasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(lblEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(15, 15, 15))
        );

        cardSalidas.setBackground(new java.awt.Color(255, 255, 255));
        cardSalidas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        cardSalidas.setAlignmentX(40.0F);
        cardSalidas.setAlignmentY(110.0F);
        cardSalidas.setName("cardStockTotal"); // NOI18N
        cardSalidas.setPreferredSize(new java.awt.Dimension(190, 160));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Salidas");

        lblSalidas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSalidas.setForeground(new java.awt.Color(0, 0, 0));
        lblSalidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalidas.setText("350");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Este mes");

        javax.swing.GroupLayout cardSalidasLayout = new javax.swing.GroupLayout(cardSalidas);
        cardSalidas.setLayout(cardSalidasLayout);
        cardSalidasLayout.setHorizontalGroup(
            cardSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardSalidasLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel7)
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(lblSalidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardSalidasLayout.setVerticalGroup(
            cardSalidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardSalidasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(lblSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(14, 14, 14))
        );

        cardProductos.setBackground(new java.awt.Color(255, 255, 255));
        cardProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        cardProductos.setAlignmentX(40.0F);
        cardProductos.setAlignmentY(110.0F);
        cardProductos.setName("cardStockTotal"); // NOI18N
        cardProductos.setPreferredSize(new java.awt.Dimension(190, 160));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Productos");

        lblProductos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(0, 0, 0));
        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductos.setText("350");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Registrados");

        javax.swing.GroupLayout cardProductosLayout = new javax.swing.GroupLayout(cardProductos);
        cardProductos.setLayout(cardProductosLayout);
        cardProductosLayout.setHorizontalGroup(
            cardProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cardProductosLayout.setVerticalGroup(
            cardProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardProductosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(14, 14, 14))
        );

        panelMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        panelMovimientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 235)));

        tablaMovimientos.setBackground(new java.awt.Color(255, 255, 255));
        tablaMovimientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tablaMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Categoria", "Stock", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMovimientos.setPreferredSize(new java.awt.Dimension(225, 190));
        jScrollPane1.setViewportView(tablaMovimientos);
        if (tablaMovimientos.getColumnModel().getColumnCount() > 0) {
            tablaMovimientos.getColumnModel().getColumn(0).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(1).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(2).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(3).setResizable(false);
            tablaMovimientos.getColumnModel().getColumn(4).setResizable(false);
        }

        btnEntradaInventario.setBackground(new java.awt.Color(0, 0, 0));
        btnEntradaInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntradaInventario.setForeground(new java.awt.Color(179, 227, 4));
        btnEntradaInventario.setText("Entrada de Stock");
        btnEntradaInventario.setAlignmentX(780.0F);
        btnEntradaInventario.setAlignmentY(35.0F);
        btnEntradaInventario.setPreferredSize(new java.awt.Dimension(160, 40));
        btnEntradaInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMovimientosLayout = new javax.swing.GroupLayout(panelMovimientos);
        panelMovimientos.setLayout(panelMovimientosLayout);
        panelMovimientosLayout.setHorizontalGroup(
            panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovimientosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEntradaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelMovimientosLayout.setVerticalGroup(
            panelMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMovimientosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEntradaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtitulo3)
                            .addComponent(lblInventario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelMovimientos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cardStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(cardEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(cardSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(cardProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardSalidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblInventario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSubtitulo3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnActualizarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(cardStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cardProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cardEntradas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(panelMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarInventarioActionPerformed
        cargarTabla();
    }//GEN-LAST:event_btnActualizarInventarioActionPerformed

    private void btnEntradaInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaInventarioActionPerformed
        mostrarDialogoEntradaStock();
    }//GEN-LAST:event_btnEntradaInventarioActionPerformed

    //METODO CARGAR TABLA
    private void cargarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tablaMovimientos.getModel();

        modelo.setRowCount(0);

        Nodo<Producto> temp = controlProducto.getProductos().getCabeza();

        int stockTotal = 0;
        int totalProductos = 0;

        while (temp != null) {

            Producto p = temp.getDato();

            String estado;

            if (p.getStock() <= 5) {
                estado = "Stock Bajo";
            } else {
                estado = "Disponible";
            }

            modelo.addRow(new Object[]{
                p.getCodigo(),
                p.getNombre(),
                p.getCategoria(),
                p.getStock(),
                estado
            });

            stockTotal += p.getStock();
            totalProductos++;

            temp = temp.getSiguiente();
        }

        lblStockTotal.setText(String.valueOf(stockTotal));
        lblProductos.setText(String.valueOf(totalProductos));
        lblEntradas.setText(String.valueOf(DatosSistema.totalEntradas));
        lblSalidas.setText(String.valueOf(DatosSistema.totalSalidas));

    }

    //FORMULARIO ENTRADA DE STOCK
    private void mostrarDialogoEntradaStock() {

        JComboBox<Producto> cmbProductos = new JComboBox<>();

        Nodo<Producto> temp = controlProducto.getProductos().getCabeza();

        while (temp != null) {

            cmbProductos.addItem(temp.getDato());

            temp = temp.getSiguiente();
        }

        JTextField txtCantidad = new JTextField();

        Object[] campos = {
            "Producto:", cmbProductos,
            "Cantidad a ingresar:", txtCantidad
        };

        int r = JOptionPane.showConfirmDialog(
                this,
                campos,
                "Entrada de Stock",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (r == JOptionPane.OK_OPTION) {

            try {

                Producto producto = (Producto) cmbProductos.getSelectedItem();

                int cantidad = Integer.parseInt(txtCantidad.getText());

                producto.setStock(producto.getStock() + cantidad);

                DatosSistema.totalEntradas += cantidad;

                DatosSistema.movimientos.agregar(
                        new Movimiento(
                                LocalDate.now().toString(),
                                "ENTRADA",
                                producto.getNombre(),
                                cantidad,
                                "Ingreso de stock"
                        )
                );

                cargarTabla();

                JOptionPane.showMessageDialog(
                        this,
                        "Stock actualizado correctamente."
                );

            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(
                        this,
                        "Ingrese una cantidad válida."
                );
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarInventario;
    private javax.swing.JButton btnEntradaInventario;
    private javax.swing.JPanel cardEntradas;
    private javax.swing.JPanel cardProductos;
    private javax.swing.JPanel cardSalidas;
    private javax.swing.JPanel cardStock;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEntradas;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblSalidas;
    private javax.swing.JLabel lblStockTotal;
    private javax.swing.JLabel lblSubtitulo3;
    private javax.swing.JPanel panelMovimientos;
    private javax.swing.JTable tablaMovimientos;
    // End of variables declaration//GEN-END:variables
}
